### ISSUE TITLE
DocumentNotExistsException: Firebase document not exists

### ISSUE THREAD

**Issue by brianblaise** [abdularis/Track-My-Location#1]
After signing up and following all necessary steps, I am getting an error while trying to share my location. I don't see my Device Id and neither does the map. Also my Firestore dashboard is empty, no collection, nothing. Any help will be appreciated

**Comment by MLucien** [comment]
Hi Brian, did you manage to solve this issue?

**Comment by brianblaise** [comment]
I tried and was not successful

**Comment by sid1509** [comment]
has anyone solved this issue yet? Or found a git similar to it?

**Comment by tpsmage** [comment]
having same issue

**Comment by abdularis** [comment]
I found the issue, the cause is in the firebase functions (server) I've fixed it

**Comment by abdularis** [comment]
you can try it by creating new account on the app
