### ISSUE TITLE
could not syn project 

### ISSUE THREAD

**Issue by DEXANI** [abdularis/Track-My-Location#2]
Could not get unknown property 'TrackMyLocation_GoogleMapsAPIKey' for BuildType_Decorated{name=debug, debuggable=true, testCoverageEnabled=false, jniDebuggable=false, pseudoLocalesEnabled=false, renderscriptDebuggable=false, renderscriptOptimLevel=3, minifyEnabled=false, zipAlignEnabled=true, signingConfig=SigningConfig_Decorated{name=debug, storeFile=C:\Users\singh\.android\debug.keystore, storePassword=android, keyAlias=AndroidDebugKey, keyPassword=android, storeType=C:\Users\singh\.android\debug.keystore, v1SigningEnabled=true, v2SigningEnabled=true}, embedMicroApp=false, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}} of type com.android.build.gradle.internal.dsl.BuildType.
Open File

**Comment by MLucien** [comment]
Did you replace with your wown google maps api key?

**Comment by abdularis** [comment]
Hello,
I generate string resource called _google_maps_api_key_ in the _app/build.gradle_ file using gradle property called _TrackMyLocation_GoogleMapsAPIKey_  
you can defined the property in gradle.properties file in the root project, but I recommend to defined in the global gradle.properties file located in ~/.gradle/gradle.properties (linux).
Hope that help.

![screenshot_2019-01-15_21-48-41](https://user-images.githubusercontent.com/22021261/51189198-1beaf700-1912-11e9-8513-559f0a936522.png)

**Comment by DEXANI** [comment]
Can you send an proper working project to singh.anirudhbp@gmail.com bec currently I am new to studio

**Comment by MLucien** [comment]
can you rather upload an updated project?

**Comment by abdularis** [comment]
I create TrackMyLocation_GoogleMapsAPIKey in the global gradle.properties file so that it would not get committed into version control

**Comment by ils-aashishj** [comment]
What is the solution?

**Comment by adgarboc** [comment]
![Track-My-Location](https://user-images.githubusercontent.com/25888082/60281143-f8b57200-98c9-11e9-95ec-4d5b940a8d98.jpg)
